export default(routes: string[]) => {
  const toSnakeCaseUpperCase = (string: string) => string.replace(/-/g, '_').toUpperCase()

  return `/* eslint-disable */

// This file was autogenerated

export enum Route {
  ${routes.map((route) => `${toSnakeCaseUpperCase(route)} = '${route}'`).join(',\n  ')}
}`
}